# Cloud Build Pipeline - The Nervous System
# Runs lean CD: Build + Migrate + Deploy + Smoke Test

steps:
  # Step 1: Build production image with Kaniko (layer caching enabled)
  # Starts immediately (no waitFor)
  - name: 'gcr.io/kaniko-project/executor:latest'
    id: 'build-prod-image'
    args:
      - --destination=europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/kura-backend:latest
      - --cache=true
      - --cache-ttl=168h
      - --context=dir://backend
      - --dockerfile=backend/Dockerfile.prod
    timeout: '1200s'
    waitFor: ['-']  # Start immediately

  # Step 2: Run migrations (IN PARALLEL with build)
  # The migrator uses the EXISTING production image, so it's safe to run in parallel
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'run-migrations'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run jobs execute kura-migrator \
          --region=europe-west1 \
          --wait
    waitFor: ['-']  # Start immediately (parallel with build)

  # Step 3: Deploy to Cloud Run
  # SAFETY: Waits for BOTH build AND migrations to complete before deployment
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy kura-backend \
          --image=europe-west1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/kura-backend:latest \
          --region=europe-west1 \
          --platform=managed \
          --allow-unauthenticated
    waitFor: ['build-prod-image', 'run-migrations']  # Wait for BOTH

  # Step 4: Production Smoke Tests (Fast Verification)
  - name: 'curlimages/curl:latest'
    id: 'smoke-tests'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "ðŸ” Running production smoke tests..."
        sleep 5
        curl -f https://api.kuraos.ai/health || exit 1
        curl -I https://app.kuraos.ai 2>&1 | grep -E "HTTP.*[23]0" || exit 1
        echo "âœ… Production endpoints healthy"
    timeout: '120s'
    waitFor: ['deploy']

# Use high-CPU machine for faster builds (Kaniko cache decompression)
options:
  machineType: 'E2_HIGHCPU_8'
  
timeout: '3600s'

