# Cloud Build Pipeline - The Nervous System
# Runs lean CD: Build + Migrate + Deploy + Smoke Test

steps:
  # Step 1: Build production image with Kaniko (layer caching enabled)
  - name: 'gcr.io/kaniko-project/executor:latest'
    id: 'build-prod-image'
    args:
      - --destination=gcr.io/$PROJECT_ID/kura-backend:$COMMIT_SHA
      - --destination=gcr.io/$PROJECT_ID/kura-backend:latest
      - --cache=true
      - --cache-ttl=168h
      - --context=dir://backend
      - --dockerfile=backend/Dockerfile
    timeout: '1200s'

  # Step 2: Run migrations
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'run-migrations'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run jobs execute kura-migrator \
          --region=europe-west1 \
          --wait
    waitFor: ['build-prod-image']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    id: 'deploy'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy kura-backend \
          --image=gcr.io/$PROJECT_ID/kura-backend:$COMMIT_SHA \
          --region=europe-west1 \
          --platform=managed \
          --allow-unauthenticated
    waitFor: ['run-migrations']

  # Step 4: Production Smoke Tests (Fast Verification)
  - name: 'curlimages/curl:latest'
    id: 'smoke-tests'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "ðŸ” Running production smoke tests..."
        sleep 5
        curl -f https://api.kuraos.ai/health || exit 1
        curl -I https://app.kuraos.ai 2>&1 | grep -E "HTTP.*[23]0" || exit 1
        echo "âœ… Production endpoints healthy"
    timeout: '120s'
    waitFor: ['deploy']

# Use high-CPU machine for faster builds (Kaniko cache decompression)
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  
timeout: '3600s'

images:
  - 'gcr.io/$PROJECT_ID/kura-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/kura-backend:latest'
