"""sync_prod_schema_hotfix

Revision ID: 230fd3513186
Revises: h8901bcdef2
Create Date: 2025-12-22 15:21:42.716762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '230fd3513186'
down_revision: Union[str, Sequence[str], None] = 'h8901bcdef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('availability_blocks', 'schedule_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('availability_schedules', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('availability_schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('form_templates', 'service_mode')
    op.drop_column('form_templates', 'scheduling_type')
    op.alter_column('service_types', 'scheduling_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('CALENDAR', 'FIXED_DATE', name='schedulingtype'),
               nullable=False,
               existing_server_default=sa.text("'CALENDAR'::character varying"))
    op.create_index(op.f('ix_service_types_schedule_id'), 'service_types', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_specific_availability_schedule_id'), 'specific_availability', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_time_off_schedule_id'), 'time_off', ['schedule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_off_schedule_id'), table_name='time_off')
    op.drop_index(op.f('ix_specific_availability_schedule_id'), table_name='specific_availability')
    op.drop_index(op.f('ix_service_types_schedule_id'), table_name='service_types')
    op.alter_column('service_types', 'scheduling_type',
               existing_type=sa.Enum('CALENDAR', 'FIXED_DATE', name='schedulingtype'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'CALENDAR'::character varying"))
    op.add_column('form_templates', sa.Column('scheduling_type', postgresql.ENUM('CALENDAR', 'FIXED_DATE', name='schedulingtype'), server_default=sa.text("'CALENDAR'::schedulingtype"), autoincrement=False, nullable=False))
    op.add_column('form_templates', sa.Column('service_mode', postgresql.ENUM('ONE_ON_ONE', 'GROUP', name='servicemode'), server_default=sa.text("'ONE_ON_ONE'::servicemode"), autoincrement=False, nullable=False))
    op.alter_column('availability_schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('availability_schedules', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('availability_blocks', 'schedule_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
