"""v070_patient_birth_data

Revision ID: 2c6c2da46142
Revises: 6a1e2cfaaf18
Create Date: 2025-12-10 12:01:34.180550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c6c2da46142'
down_revision: Union[str, Sequence[str], None] = '6a1e2cfaaf18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('birth_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('patients', sa.Column('birth_time', sa.String(length=10), nullable=True))
    op.add_column('patients', sa.Column('birth_place', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'birth_place')
    op.drop_column('patients', 'birth_time')
    op.drop_column('patients', 'birth_date')
    # ### end Alembic commands ###
