"""Add booking engine tables (ServiceType, AvailabilityBlock, TimeOff, Booking)

Revision ID: 3f58d1acf653
Revises: 748e186255ba
Create Date: 2025-12-11 22:16:48.053112

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "3f58d1acf653"
down_revision: Union[str, Sequence[str], None] = "748e186255ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "availability_blocks",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("day_of_week", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.String(length=5), nullable=False),
        sa.Column("end_time", sa.String(length=5), nullable=False),
        sa.Column(
            "effective_from",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("effective_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_availability_blocks_user_id"),
        "availability_blocks",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "service_types",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "kind",
            postgresql.ENUM(
                "ONE_ON_ONE", "GROUP", name="servicemode", create_type=False
            ),
            nullable=False,
        ),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("intake_form_id", sa.Uuid(), nullable=True),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["intake_form_id"],
            ["form_templates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_service_types_organization_id"),
        "service_types",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "time_off",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("start_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reason", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_time_off_user_id"), "time_off", ["user_id"], unique=False)
    op.create_table(
        "bookings",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("service_type_id", sa.Uuid(), nullable=False),
        sa.Column("therapist_id", sa.Uuid(), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "CONFIRMED",
                "CANCELLED",
                "COMPLETED",
                "NO_SHOW",
                name="bookingstatus",
            ),
            nullable=False,
        ),
        sa.Column("stripe_payment_intent_id", sa.String(length=255), nullable=True),
        sa.Column("stripe_payment_status", sa.String(length=50), nullable=True),
        sa.Column("amount_paid", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("patient_notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_type_id"],
            ["service_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["therapist_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bookings_organization_id"),
        "bookings",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bookings_patient_id"), "bookings", ["patient_id"], unique=False
    )
    op.create_index(
        op.f("ix_bookings_service_type_id"),
        "bookings",
        ["service_type_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bookings_stripe_payment_intent_id"),
        "bookings",
        ["stripe_payment_intent_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bookings_therapist_id"), "bookings", ["therapist_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bookings_therapist_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_stripe_payment_intent_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_service_type_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_patient_id"), table_name="bookings")
    op.drop_index(op.f("ix_bookings_organization_id"), table_name="bookings")
    op.drop_table("bookings")
    op.drop_index(op.f("ix_time_off_user_id"), table_name="time_off")
    op.drop_table("time_off")
    op.drop_index(op.f("ix_service_types_organization_id"), table_name="service_types")
    op.drop_table("service_types")
    op.drop_index(
        op.f("ix_availability_blocks_user_id"), table_name="availability_blocks"
    )
    op.drop_table("availability_blocks")
    # ### end Alembic commands ###
