"""v137_referral_conversions_and_bonus_slots

Revision ID: 4d941a79878b
Revises: n4567ijkl8901
Create Date: 2026-01-06 01:57:34.032032

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4d941a79878b"
down_revision: Union[str, Sequence[str], None] = "n4567ijkl8901"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "referral_conversions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("referrer_org_id", sa.Uuid(), nullable=False),
        sa.Column("referee_org_id", sa.Uuid(), nullable=False),
        sa.Column(
            "reward_type",
            sa.Enum("CREDITS", "SLOT", "BOTH", name="rewardtype"),
            nullable=False,
        ),
        sa.Column("credits_awarded", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PAID", name="conversionstatus"),
            nullable=False,
        ),
        sa.Column(
            "converted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["referee_org_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["referrer_org_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("referee_org_id"),
    )
    op.create_index(
        op.f("ix_referral_conversions_referrer_org_id"),
        "referral_conversions",
        ["referrer_org_id"],
        unique=False,
    )
    op.add_column(
        "organizations",
        sa.Column(
            "bonus_patient_slots", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "bonus_patient_slots")
    op.drop_index(
        op.f("ix_referral_conversions_referrer_org_id"),
        table_name="referral_conversions",
    )
    op.drop_table("referral_conversions")
    # Drop ENUM types (SafeMigration: must use IF EXISTS)
    op.execute("DROP TYPE IF EXISTS rewardtype")
    op.execute("DROP TYPE IF EXISTS conversionstatus")
    # ### end Alembic commands ###
