"""Make clinical_entries.author_id nullable for public forms

Revision ID: 5421c9b1cd68
Revises: b8697b17c51a
Create Date: 2025-12-10 21:26:21.231250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5421c9b1cd68'
down_revision: Union[str, Sequence[str], None] = 'b8697b17c51a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clinical_entries', 'author_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('clinical_entries', 'author_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
