"""add_password_reset_fields

Revision ID: 59d8c633dbe5
Revises: 264a97cb8a78
Create Date: 2025-12-28 01:19:40.450706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59d8c633dbe5'
down_revision: Union[str, Sequence[str], None] = '264a97cb8a78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anonymous_datasets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.Enum('CLINICAL_NOTE', 'TRANSCRIPT', 'CHAT_ANALYSIS', name='datasettype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('ai_usage_logs', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('ai_usage_logs', 'provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'vertex-google'::character varying"))
    op.alter_column('ai_usage_logs', 'model_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'gemini-2.5-flash'::character varying"))
    op.alter_column('ai_usage_logs', 'task_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'clinical_analysis'::character varying"))
    op.alter_column('ai_usage_logs', 'tokens_input',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('ai_usage_logs', 'tokens_output',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('ai_usage_logs', 'cost_provider_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('ai_usage_logs', 'cost_user_credits',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('ai_usage_logs', 'activity_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index('ix_ai_usage_model', 'ai_usage_logs', ['model_id'], unique=False)
    op.create_index('ix_ai_usage_org_date', 'ai_usage_logs', ['organization_id', 'created_at'], unique=False)
    op.drop_constraint('ai_usage_logs_entry_id_fkey', 'ai_usage_logs', type_='foreignkey')
    op.create_foreign_key(None, 'ai_usage_logs', 'clinical_entries', ['clinical_entry_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'ai_usage_logs', 'patients', ['patient_id'], ['id'])
    op.drop_column('ai_usage_logs', 'entry_id')
    op.alter_column('availability_blocks', 'schedule_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('availability_schedules', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('availability_schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('form_templates', 'scheduling_type')
    op.drop_column('form_templates', 'service_mode')
    op.alter_column('service_types', 'scheduling_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('CALENDAR', 'FIXED_DATE', name='schedulingtype'),
               nullable=False,
               existing_server_default=sa.text("'CALENDAR'::character varying"))
    op.create_index(op.f('ix_service_types_schedule_id'), 'service_types', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_specific_availability_schedule_id'), 'specific_availability', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_time_off_schedule_id'), 'time_off', ['schedule_id'], unique=False)
    op.add_column('users', sa.Column('password_reset_token', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('password_reset_expires', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_password_reset_token'), 'users', ['password_reset_token'], unique=False)
    op.drop_column('users', 'is_super_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_super_admin', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_password_reset_token'), table_name='users')
    op.drop_column('users', 'password_reset_expires')
    op.drop_column('users', 'password_reset_token')
    op.drop_index(op.f('ix_time_off_schedule_id'), table_name='time_off')
    op.drop_index(op.f('ix_specific_availability_schedule_id'), table_name='specific_availability')
    op.drop_index(op.f('ix_service_types_schedule_id'), table_name='service_types')
    op.alter_column('service_types', 'scheduling_type',
               existing_type=sa.Enum('CALENDAR', 'FIXED_DATE', name='schedulingtype'),
               type_=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'CALENDAR'::character varying"))
    op.add_column('form_templates', sa.Column('service_mode', postgresql.ENUM('ONE_ON_ONE', 'GROUP', name='servicemode'), server_default=sa.text("'ONE_ON_ONE'::servicemode"), autoincrement=False, nullable=False))
    op.add_column('form_templates', sa.Column('scheduling_type', postgresql.ENUM('CALENDAR', 'FIXED_DATE', name='schedulingtype'), server_default=sa.text("'CALENDAR'::schedulingtype"), autoincrement=False, nullable=False))
    op.alter_column('availability_schedules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('availability_schedules', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('availability_blocks', 'schedule_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('ai_usage_logs', sa.Column('entry_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ai_usage_logs', type_='foreignkey')
    op.drop_constraint(None, 'ai_usage_logs', type_='foreignkey')
    op.create_foreign_key('ai_usage_logs_entry_id_fkey', 'ai_usage_logs', 'clinical_entries', ['entry_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_ai_usage_org_date', table_name='ai_usage_logs')
    op.drop_index('ix_ai_usage_model', table_name='ai_usage_logs')
    op.alter_column('ai_usage_logs', 'activity_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('ai_usage_logs', 'cost_user_credits',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('ai_usage_logs', 'cost_provider_usd',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    op.alter_column('ai_usage_logs', 'tokens_output',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('ai_usage_logs', 'tokens_input',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('ai_usage_logs', 'task_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'clinical_analysis'::character varying"))
    op.alter_column('ai_usage_logs', 'model_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'gemini-2.5-flash'::character varying"))
    op.alter_column('ai_usage_logs', 'provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'vertex-google'::character varying"))
    op.alter_column('ai_usage_logs', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_table('anonymous_datasets')
    # ### end Alembic commands ###
