"""v070_intake_forms_engine

Revision ID: 6a1e2cfaaf18
Revises: d1670cffdea6
Create Date: 2025-12-10 11:41:01.739356

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "6a1e2cfaaf18"
down_revision: Union[str, Sequence[str], None] = "d1670cffdea6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add FORM_SUBMISSION to entrytype enum
    op.execute("ALTER TYPE entrytype ADD VALUE IF NOT EXISTS 'FORM_SUBMISSION'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "form_templates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("organization_id", sa.Uuid(), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("schema", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "risk_level",
            sa.Enum("LOW", "MEDIUM", "HIGH", "CRITICAL", name="risklevel"),
            nullable=False,
        ),
        sa.Column(
            "therapy_type",
            sa.Enum(
                "GENERAL",
                "ASTROLOGY",
                "SOMATIC",
                "PSYCHEDELIC",
                "INTEGRATION",
                name="therapytype",
            ),
            nullable=False,
        ),
        sa.Column(
            "form_type",
            sa.Enum(
                "INTAKE", "PRE_SESSION", "POST_SESSION", "FEEDBACK", name="formtype"
            ),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_form_templates_organization_id"),
        "form_templates",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "form_assignments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("patient_id", sa.Uuid(), nullable=False),
        sa.Column("template_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "SENT", "OPENED", "COMPLETED", "EXPIRED", name="formassignmentstatus"
            ),
            nullable=False,
        ),
        sa.Column("token", sa.String(length=64), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["form_templates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_form_assignments_patient_id"),
        "form_assignments",
        ["patient_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_form_assignments_template_id"),
        "form_assignments",
        ["template_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_form_assignments_token"), "form_assignments", ["token"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_form_assignments_token"), table_name="form_assignments")
    op.drop_index(
        op.f("ix_form_assignments_template_id"), table_name="form_assignments"
    )
    op.drop_index(op.f("ix_form_assignments_patient_id"), table_name="form_assignments")
    op.drop_table("form_assignments")
    op.drop_index(
        op.f("ix_form_templates_organization_id"), table_name="form_templates"
    )
    op.drop_table("form_templates")
    # ### end Alembic commands ###
