"""Add clinical_entries table

Revision ID: 8506f66d6628
Revises: 347484b0863b
Create Date: 2025-12-09 15:52:16.500478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8506f66d6628'
down_revision: Union[str, Sequence[str], None] = '347484b0863b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinical_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('entry_type', sa.Enum('SESSION_NOTE', 'AUDIO', 'DOCUMENT', 'AI_ANALYSIS', 'ASSESSMENT', name='entrytype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('entry_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('happened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinical_entries_patient_id'), 'clinical_entries', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinical_entries_patient_id'), table_name='clinical_entries')
    op.drop_table('clinical_entries')
    # ### end Alembic commands ###
