"""v070_public_token

Revision ID: 8fe39af7b898
Revises: b44ae9d1e223
Create Date: 2025-12-10 12:46:36.850250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fe39af7b898'
down_revision: Union[str, Sequence[str], None] = 'b44ae9d1e223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('form_templates', sa.Column('public_token', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_form_templates_public_token'), 'form_templates', ['public_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_form_templates_public_token'), table_name='form_templates')
    op.drop_column('form_templates', 'public_token')
    # ### end Alembic commands ###
