"""add_views_count_to_form_templates

Revision ID: a8651949a70d
Revises: c603b797ed14
Create Date: 2026-01-08 03:30:04.560738

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a8651949a70d"
down_revision: Union[str, Sequence[str], None] = "c603b797ed14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Add column as nullable
    op.add_column(
        "form_templates", sa.Column("views_count", sa.Integer(), nullable=True)
    )

    # 2. Update existing rows to 0
    op.execute("UPDATE form_templates SET views_count = 0")

    # 3. Set column to NOT NULL
    op.alter_column("form_templates", "views_count", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("form_templates", "views_count")
    # ### end Alembic commands ###
