"""Add ON DELETE SET NULL to ai_usage_logs entry_id

Revision ID: b8697b17c51a
Revises: 8fe39af7b898
Create Date: 2025-12-10 18:56:56.253207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8697b17c51a'
down_revision: Union[str, Sequence[str], None] = '8fe39af7b898'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ai_usage_logs_entry_id_fkey', 'ai_usage_logs', type_='foreignkey')
    op.create_foreign_key(None, 'ai_usage_logs', 'clinical_entries', ['entry_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ai_usage_logs', type_='foreignkey')
    op.create_foreign_key('ai_usage_logs_entry_id_fkey', 'ai_usage_logs', 'clinical_entries', ['entry_id'], ['id'])
    # ### end Alembic commands ###
