"""v1.6.0_crm_leads_foundation

Revision ID: c603b797ed14
Revises: 190c2b058ca0
Create Date: 2026-01-08 03:36:17.044442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c603b797ed14'
down_revision: Union[str, Sequence[str], None] = '190c2b058ca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ai_pipeline_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_pipeline_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('ai_pipeline_configs_name_key', 'ai_pipeline_configs', type_='unique')
    op.drop_index('ix_ai_pipeline_configs_name', table_name='ai_pipeline_configs')
    op.create_index(op.f('ix_ai_pipeline_configs_name'), 'ai_pipeline_configs', ['name'], unique=True)
    op.alter_column('ai_task_config_history', 'changed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_task_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('clinical_entries', 'is_ghost',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('leads', sa.Column('shadow_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('leads', sa.Column('sherlock_metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'sherlock_metrics')
    op.drop_column('leads', 'shadow_profile')
    op.alter_column('clinical_entries', 'is_ghost',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('ai_task_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_task_config_history', 'changed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_ai_pipeline_configs_name'), table_name='ai_pipeline_configs')
    op.create_index('ix_ai_pipeline_configs_name', 'ai_pipeline_configs', ['name'], unique=False)
    op.create_unique_constraint('ai_pipeline_configs_name_key', 'ai_pipeline_configs', ['name'])
    op.alter_column('ai_pipeline_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_pipeline_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
