"""add_karma_score_to_organization

Revision ID: cd40ac38c48c
Revises: m3456ghij7890
Create Date: 2026-01-02 09:56:20.022240

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cd40ac38c48c"
down_revision: Union[str, Sequence[str], None] = "m3456ghij7890"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # First ensure target_timezone column exists (may not exist in fresh DBs)
    # The column was added via manual hotfix in prod but needs creation here
    conn = op.get_bind()
    result = conn.execute(
        sa.text("""
        SELECT column_name FROM information_schema.columns 
        WHERE table_name='bookings' AND column_name='target_timezone'
    """)
    )
    if result.fetchone() is None:
        # Column doesn't exist, add it
        op.add_column(
            "bookings",
            sa.Column(
                "target_timezone",
                sa.String(length=64),
                nullable=True,
                server_default=sa.text("'Europe/Madrid'"),
            ),
        )
    else:
        # Column exists (prod), just alter the type
        op.alter_column(
            "bookings",
            "target_timezone",
            existing_type=sa.VARCHAR(length=50),
            type_=sa.String(length=64),
            existing_nullable=True,
            existing_server_default=sa.text("'Europe/Madrid'::character varying"),
        )

    op.add_column(
        "organizations",
        sa.Column("karma_score", sa.Integer(), nullable=False, server_default="0"),
    )

    # Backfill: Generate referral codes for existing organizations
    op.execute("""
        UPDATE organizations
        SET referral_code = 'KURA-' || UPPER(SUBSTRING(MD5(RANDOM()::TEXT) FROM 1 FOR 6))
        WHERE referral_code IS NULL OR referral_code = '';
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "karma_score")
    op.alter_column(
        "bookings",
        "target_timezone",
        existing_type=sa.String(length=64),
        type_=sa.VARCHAR(length=50),
        existing_nullable=True,
        existing_server_default=sa.text("'Europe/Madrid'::character varying"),
    )
    # ### end Alembic commands ###
